apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: podinfoapp1-deployment
spec:
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: podinfoapp1-deployment
