apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfoapp1-rbac
  namespace: n1

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: podinfoapp1-rbac
  namespace: n1
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch","list","get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: podinfoapp1-rbac
  namespace: n1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podinfoapp1-rbac
subjects:
  - kind: ServiceAccount
    name: podinfoapp1-rbac
    namespace: n1
